project:
  type: website
  
resources:
  - "assets/*"
  - "files/*"
  
website:
  title: "David C. Porter"
  page-footer:
    left: "Made with [Quarto](https://quarto.org/)"
  navbar:
    pinned: true
    search: false
    right:
      - href: index.qmd
        text: Home
      - teaching.qmd
      - research.qmd
      - href: files/DavidPorterCV2024.pdf
        text: CV
      - href: https://www.manchustudiesgroup.org/introduction-to-manchu-in-21-lessons/
        text: Manchu Study Resources

format:
  html:
    theme: [litera, assets/fonts.scss, assets/styles.scss]
    toc: false
    page-layout: full

editor: visual

# setup help: https://ucsb-meds.github.io/creating-quarto-websites/