---
title: "Teaching"
---

*My teaching covers a wide range of periods and topics in Chinese and Japanese history, as well as that of East Asia as a region. I pay particular attention in my courses to questions of identity, empire-building, and cross-cultural contact, especially along the Inner Asian and Southeast Asian frontiers of China.*

### Introduction to East Asian History

#### Undergraduate lecture course

This course introduces the history of East Asia – China and its Inner Asian frontiers, Japan, and Korea – from ancient times to about the year 1600.

[Syllabus](files/Introduction%20to%20East%20Asian%20History%20Syllabus.pdf){.btn .btn-outline-primary .btn role="button"}

### Rebellion and Revolution in Modern China

#### Undergraduate lecture course

This course focuses on violent attempts to change the political or social order, events often called "rebellions" or "revolutions," especially in the period between 1839 and 1949.

[Syllabus](files/Rebellion%20and%20Revolution%20in%20Modern%20China%20Syllabus.pdf){.btn .btn-outline-primary .btn role="button"}

### Borderlands of Modern China

#### Undergraduate lecture course

This course explores how China came to acquire its current shape and population through centuries of imperial conquest, colonial expansion, and cross-ethnic alliance building along its northwestern and southwestern borders.

[Syllabus](files/Borderlands%20of%20Modern%20China%20Syllabus.pdf){.btn .btn-outline-primary .btn role="button"}

### Identity in Early Modern East Asia

#### Undergraduate seminar

This advanced undergraduate seminar explores identity and the politics of identity in China, Japan, and Korea between roughly 1200 and 1900.

[Syllabus](files/Identity%20in%20Early%20Modern%20East%20Asia%20syllabus.pdf){.btn .btn-outline-primary .btn role="button"}

### Late Imperial China

#### Undergraduate seminar

This course explores the history of China from the founding of the Ming dynasty through the height of the Qing, from about 1368 to 1800, with a thematic approach, looking at topics like governance, economy, society, culture, and environment.

[Syllabus](files/Late%20Imperial%20China%20Syllabus.pdf){.btn .btn-outline-primary .btn role="button"}

### Age of Samurai: Japan from Tokugawa to Meiji

#### Undergraduate seminar

This course explores the history of Japan from its post-Warring States Era unification in the late 16th Century to its period of political restructuring in the wake of the Meiji Restoration in 1868.

[Syllabus](files/Age%20of%20Samurai%20syllabus.pdf){.btn .btn-outline-primary .btn role="button"}

### Society, Culture, and Identity in Early Modern Japan

#### Undergraduate lecture course

This course explores the dynamics of Japanese society during the Tokugawa era, which lasted from 1600-1868, with an exploration of topics like the workings of the status system, family structure and ideas about gender, the conquest and management of Ainu lands in the northern island of Hokkaidō, and the spatial and social organization of Japanese cities and villages.

[Syllabus](files/Society%20Culture%20and%20Identity%20in%20Early%20Modern%20Japan%20syllabus.pdf){.btn .btn-outline-primary .btn role="button"}

### Empire and Identity in Qing China

#### Undergraduate seminar

This seminar examines how identity was produced and maintained in a context very different from our own: the Qing empire, which ruled China and much of Inner Asia from 1644 until 1912. It examines topics like gender, ethnicity, status, religion, sexuality, empire, and colonialism.

[Syllabus](files/Empire%20and%20Identity%20in%20Qing%20China%20Syllabus.pdf){.btn .btn-outline-primary .btn role="button"}

### Modern China

#### Undergraduate lecture course

This course offers a history of China from the Manchu conquest in 1644, which established the rule of the final imperial dynasty, the Qing, over China, through the present day.

[Syllabus](files/Modern%20China%20syllabus.pdf){.btn .btn-outline-primary .btn role="button"}
